# Model architecture and optimization parameters

model_type: LSTM

lstm_in_size: 100
lstm_hidden_size: 256
lstm_num_layers: 3
lstm_bidirectional: False
lstm_dropout: 0.5

decoder_hidden_size: 512
activation: false

loss: MSE
opt: Adam
lr: 0.0002

# Training dataset parameters

training:
  bs: 1024

# Augmentation params

augmentation:
  shift:
    - -2
    - 2
  add:
    - -0.05
    - 0.05
  random_noise: 0.0
  scale:
    - 0.99
    - 1.01
  dropping_aug:
    - 0.05
    - 0.1

# Data sources and formula converters

data:
  converter: vector
  converter_settings:
    normalizer: means
  is_classifier: False

  representations: /home/boiko/mra/training_data.tsv.gz
  #representations: test.tsv.gz